defaults:
  - c_core_magnetic_pointnet2_ssg
  - c_core_magnetic_deal_protocol
  - _self_

experiment:
  name: "C_CORE_MAGNETIC_POINTNET2_SSG_DEAL_FROM_BASE"
  model_name: "POINTNET2_SSG_C_CORE_MAGNETIC_DEAL"
  model_tag: "from-base-150ep"
  batch_size: 1
  num_body_points: 0
  view_geometry_points: 16384
  primary_view_geometry_points: 16384
  secondary_view_geometry_points: 16384
  shared_shift_view_geometry_points: 16384
  eval_view_geometry_points: 16384
  eval_aligned_view_geometry_points: 16384
  eval_shifted_view_geometry_points: 16384
  multi_gpu_strategy: "single"
  init_ckpt: ""
  resume_ckpt: ""
  resume_full_state: False
