defaults:
  - c_core_magnetic_smart
  - c_core_magnetic_deal_protocol
  - _self_

experiment:
  name: "C_CORE_MAGNETIC_SMART_DEAL_FROM_BASE"
  model_name: "SMART_C_CORE_MAGNETIC_DEAL"
  model_tag: "from-base-150ep"
  batch_size: 1
  multi_gpu_strategy: "single"
  init_ckpt: ""
  resume_ckpt: ""
  resume_full_state: False

