defaults:
  - drivaerml_point_transformer_v3
  - _self_

experiment:
  name: "DrivAerML_POINT_TRANSFORMER_V3_DENSITY_SENSITIVE"
  model_name: "POINT_TRANSFORMER_V3"
  epochs: 250
  architecture:
    order: [z, hilbert]
    shuffle_orders: false
    voxel_density_power: 0.75
    preserve_density: true
    local_query_chunk_size: 16384
  init_ckpt: ""
  resume_ckpt: ""
  resume_full_state: False
