defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

wandb:
  project: "smart"
  entity: "parsa-vatani99-technical-university-of-munich"

experiment:
  name: "DrivAerML_SMART_DOWNSAMPLE"
  model_name: "SMART_DOWNSAMPLE"
  model_tag: ""
  random_seed: 42
  manifest_variant: "full"

  architecture:
    latent_dim: 256
    latent_geometry_points: 4096
    subsampled_geometry_points: 16384
    subsampled_geometry_with_replacement: True
    num_encoder_decoder_blocks: 6
    pos_scale_factor: 100

  optimizer: "adamw"
  loss_fn: "rel_l2"
  scheduler: "cosine"
  scheduler_warumup_fraction: 0.2
  batch_size: 1
  epochs: 300
  learning_rate: 2.e-4
  gradient_norm: null
  amp: True
  precision: "float16"
  log_every_n_steps: 10
  inspect_first_sample: False
  resume_ckpt: ""
  resume_full_state: False
  init_ckpt: ""
  wandb_watch_model: False
  multi_gpu_strategy: "single"

  dataset: "DrivAerML"
  data_path: "/mnt/ssdraid/parsa/drivaerml_preprocessed"
  num_workers: 8
  prefetch_factor: 4
  pin_memory: True
  cuda_batch_prefetch: True
  geometry_epoch_seeded_sampling: False
  num_body_points: 0
  num_surface_points: 65536
  num_volume_points: 65536
  scale_positions: False

  view_geometry_points: 131072
  primary_view_geometry_points: 131072
  secondary_view_geometry_points: 32768
  secondary_view_subsampled_geometry_points: 4096
  eval_aligned_view_geometry_points: 131072
  eval_shifted_view_geometry_points: 32768
  eval_shifted_subsampled_geometry_points: 4096

  train_primary_sampling_mode: "uniform_wor"
  train_secondary_sampling_mode: "uniform_wor"
  eval_aligned_sampling_mode: "uniform_wor"
  eval_shifted_sampling_mode: "uniform_wor"
  inverse_density_beta: 0.0
  mixed_inverse_density_prob: 0.0

  prediction_consistency_weight: 1.0
  prediction_consistency_smooth_l1_beta: 0.05
  use_latent_consistency: False
  consistency_warmup_epochs: 30
  fuse_consistency_views: False
