defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

wandb:
  project: "smart"
  entity: "parsa-vatani99-technical-university-of-munich"

experiment:
  name: "DrivAerML_SMART_SAT"
  model_name: "SMART_SAT"
  model_tag: ""
  random_seed: 42
  manifest_variant: "full"

  architecture:
    latent_dim: 256
    latent_geometry_points: 4096
    subsampled_geometry_points: 16384
    subsampled_geometry_with_replacement: True
    num_encoder_decoder_blocks: 6
    pos_scale_factor: 100
    density_knn_k: 16
    density_neighbor_hops: 1
    density_estimator: "kde"
    latent_density_alpha: 0.25

  optimizer: "adamw"
  loss_fn: "rel_l2"
  scheduler: "cosine"
  scheduler_warumup_fraction: 0.2
  batch_size: 1
  epochs: 300
  learning_rate: 2.e-4
  gradient_norm: null
  amp: True
  precision: "float16"
  log_every_n_steps: 10
  inspect_first_sample: False
  resume_ckpt: ""
  resume_full_state: False

  dataset: "DrivAerML"
  data_path: "/mnt/ssdraid/parsa/drivaerml_preprocessed"
  num_workers: 8
  prefetch_factor: 4
  pin_memory: True
  geometry_density_cache_dtype: "float16"
  geometry_epoch_seeded_sampling: True
  num_body_points: 131072
  num_surface_points: 65536
  num_volume_points: 65536
  scale_positions: False
