defaults:
  - drivaerml_satloss7_range100
  - _self_

experiment:
  name: "DrivAerML_SMART_SATLOSS7_RANGE_100_FROM_SMART_KDE64"
  model_name: "SMART_SATLOSS7_RANGE100_KDE64"
  epochs: 150
  density_knn_k: 64
  init_ckpt: ""
  resume_ckpt: ""
  resume_full_state: False
