defaults:
  - drivaerml
  - _self_

experiment:
  name: "DrivAerML_LNO"
  model_name: "LNO"
  architecture:
    n_block: 6
    n_mode: 64
    n_dim: 128
    n_head: 8
    n_layer: 2
    attn: "Galerkin"
    activation: "GELU"
    pos_scale_factor: 1.0
    query_chunk_size: 65536
    dropout: 0.0
  num_body_points: 65536
  geometry_epoch_seeded_sampling: True
