defaults:
  - drivaerml_satloss6
  - _self_

experiment:
  name: "DrivAerML_LNO_SATLOSS6"
  model_name: "LNO_SATLOSS6"
  init_ckpt: ""
  architecture:
    n_block: 8
    n_mode: 256
    n_dim: 256
    n_head: 8
    n_layer: 2
    attn: "Galerkin"
    activation: "GELU"
    pos_scale_factor: 1.0
    query_chunk_size: 65536
    dropout: 0.0
    normalize_scores: True
    encode_score_temperature: 2.0
    decode_score_temperature: 1.0
  view_geometry_points: 65536
  eval_view_geometry_points: 65536
  batch_size: 2
  geometry_epoch_seeded_sampling: False
  cuda_batch_prefetch: True
