defaults:
  - pump_ab_upt
  - pump_deal_satloss7_protocol
  - _self_

experiment:
  name: "PUMP_AB_UPT_DEAL_FROM_BASE"
  model_name: "AB_UPT_PUMP_DEAL"
  model_tag: "from-base-150ep"
  batch_size: 1
  multi_gpu_strategy: "single"

wandb:
  mode: "disabled"
