defaults:
  - pump_mspt
  - pump_deal_satloss7_protocol
  - _self_

experiment:
  name: "PUMP_MSPT_DEAL_FROM_BASE"
  model_name: "MSPT_PUMP_DEAL"
  model_tag: "from-base-150ep"
  batch_size: 1
  multi_gpu_strategy: "single"

wandb:
  mode: "disabled"
