defaults:
  - pump_satloss7
  - _self_

experiment:
  name: "PUMP_SMART_DOWNSAMPLE"
  model_name: "SMART_PUMP_SATLOSS7_DOWNSAMPLE"
  model_tag: ""
  epochs: 150
  train_shared_shift_sampling_mode: ""
  train_primary_sampling_mode: "uniform_wor"
  train_secondary_sampling_mode: "uniform_wor"
  primary_view_geometry_points: 16384
  secondary_view_geometry_points: 4096
  secondary_view_subsampled_geometry_points: 512
  shared_shift_view_geometry_points: 0
  eval_aligned_view_geometry_points: 16384
  eval_shifted_view_geometry_points: 4096
  eval_shifted_subsampled_geometry_points: 512
  fuse_consistency_views: False
