#!/usr/bin/env python3
"""Build validated VTP geometry sources for sampling-invariance experiments.

The three methods deliberately represent different meshing mechanisms:

* ``voxel``: voxel-grid vertex clustering with quadric contraction;
* ``quadric``: volume-preserving quadric-error simplification; and
* ``feature``: feature-aware edge collapse.

Only geometry is written.  Query points and target fields remain in the
original preprocessed datasets, preserving the inference protocol.
"""

from __future__ import annotations

import argparse
import gc
import json
import math
import os
import re
import shutil
import sys
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path
from typing import Iterable

import numpy as np
from tqdm.auto import tqdm

SCRIPT_DIR = Path(__file__).resolve().parent
SMART_ROOT = SCRIPT_DIR.parent
if str(SMART_ROOT) not in sys.path:
    sys.path.insert(0, str(SMART_ROOT))

from scripts.decimate_drivaerml_vtp import (  # noqa: E402
    geometry_only,
    read_polydata,
    require_vtk,
    surface_area,
    triangulate_if_needed,
    validate_mesh,
    write_vtp,
)


DATASET_DEFAULTS = {
    "drivaerml": {
        "source_dir": Path("/mnt/ssdraid/parsa/drivaerml_surface_vtp"),
        "output_dir": Path("/mnt/ssdraid/parsa/drivaerml_surface_vtp_remesh_v2"),
        "pattern": "run_*/drivaer_*.vtp",
    },
    "pump": {
        "source_dir": Path("/mnt/ssdraid/parsa/shift_pump_surface_vtp_remesh_v2_original"),
        "output_dir": Path("/mnt/ssdraid/parsa/shift_pump_surface_vtp_remesh_v2"),
        "pattern": "sample_*/merged_surfaces.vtp",
    },
    "toy_heat_exchange": {
        "source_dir": Path("/mnt/ssdraid/parsa/toy_heat_exchange_surface_vtp"),
        "output_dir": Path("/mnt/ssdraid/parsa/toy_heat_exchange_surface_vtp_remesh_v2"),
        "pattern": "case_*/*_surface.vtp",
    },
}


def parse_ints(value: str) -> list[int]:
    values = sorted({int(item.strip()) for item in str(value).split(",") if item.strip()})
    if not values or any(item <= 1 for item in values):
        raise ValueError("--factors must be unique integers greater than one.")
    return values


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("--dataset", required=True, choices=tuple(DATASET_DEFAULTS))
    parser.add_argument("--source-dir", type=Path, default=None)
    parser.add_argument("--output-dir", type=Path, default=None)
    parser.add_argument("--results-dir", type=Path, default=None)
    parser.add_argument("--factors", default="5,10")
    parser.add_argument("--methods", default="voxel,quadric,feature")
    parser.add_argument(
        "--gpu-device",
        default="cuda:0",
        help="Retained for command compatibility; remeshing uses CPU-native mesh libraries.",
    )
    parser.add_argument("--workers", type=int, default=16, help="Independent mesh workers across all methods.")
    parser.add_argument("--max-cases", type=int, default=0)
    parser.add_argument("--case-ids", default="", help="Optional comma-separated numeric IDs.")
    parser.add_argument("--feature-angle", type=float, default=30.0)
    parser.add_argument("--isotropic-iterations", type=int, default=10)
    parser.add_argument(
        "--isotropic-seed-multiplier",
        type=float,
        default=1.5,
        help="Maximum seed-face multiple before explicit remeshing; reduces work without changing the final method.",
    )
    parser.add_argument(
        "--isotropic-seed-backend",
        choices=("meshlab_qem", "vtk_decimate_pro"),
        default="meshlab_qem",
        help=(
            "Topology-preserving preconditioner for explicit isotropic remeshing. "
            "The final mesh is always generated by MeshLab's explicit isotropic filter."
        ),
    )
    parser.add_argument("--isotropic-adjustments", type=int, default=3)
    parser.add_argument("--isotropic-max-surface-distance-percent", type=float, default=1.0)
    parser.add_argument("--face-tolerance", type=float, default=0.10)
    parser.add_argument(
        "--validate-topology",
        action="store_true",
        help="Also count boundary and non-manifold edges. This is very expensive on multi-million-face meshes.",
    )
    parser.add_argument(
        "--strict-topology",
        action="store_true",
        help=(
            "Require outputs to introduce neither non-manifold edges nor additional boundary edges relative to the source. "
            "Implies --validate-topology and is intended for audit runs."
        ),
    )
    parser.add_argument(
        "--fail-fast",
        action="store_true",
        help="Stop at the first failed mesh instead of writing a complete failure summary.",
    )
    parser.add_argument("--voxel-adjustments", type=int, default=8)
    parser.add_argument(
        "--example-factor",
        type=int,
        default=10,
        help="Reduction factor exported for the original-plus-three-method example bundle.",
    )
    parser.add_argument("--pump-repo-id", default="luminary-shift/Pump-sample")
    parser.add_argument("--pump-revision", default="main")
    parser.add_argument("--pump-count", type=int, default=100)
    parser.add_argument(
        "--delete-pump-source-after-success",
        action="store_true",
        help="Delete an original Pump VTP after all requested remesh outputs pass validation.",
    )
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def numeric_id(path: Path) -> int:
    match = re.search(r"(?:run|case|sample)_(\d+)", str(path.parent))
    if match is None:
        raise ValueError(f"Could not extract case ID from {path}")
    return int(match.group(1))


def load_mesh(path: Path, include_arrays: bool = False):
    vtk, vtk_to_numpy = require_vtk()
    poly = triangulate_if_needed(vtk, read_polydata(vtk, path))
    validation = validate_mesh(vtk, vtk_to_numpy, poly, check_topology=False)
    if not validation["positive_area"]:
        raise RuntimeError(f"Source mesh has non-positive triangles: {path}")
    if not include_arrays:
        return vtk, vtk_to_numpy, poly, None, None
    points = np.asarray(vtk_to_numpy(poly.GetPoints().GetData()), dtype=np.float32)
    cells = np.asarray(vtk_to_numpy(poly.GetPolys().GetData()), dtype=np.int64)
    if cells.size % 4 != 0 or not np.all(cells[::4] == 3):
        raise RuntimeError(f"Source mesh is not a pure triangle mesh: {path}")
    faces = np.ascontiguousarray(cells.reshape(-1, 4)[:, 1:])
    return vtk, vtk_to_numpy, poly, np.ascontiguousarray(points), faces


def build_polydata(vtk, points: np.ndarray, faces: np.ndarray):
    from vtk.util.numpy_support import numpy_to_vtk, numpy_to_vtkIdTypeArray

    result = vtk.vtkPolyData()
    vtk_points = vtk.vtkPoints()
    # Keep double precision for simplifiers that return very small valid
    # triangles. Downcasting them to float32 can turn them into zero-area
    # cells before VTK writes the VTP.
    point_array = np.asarray(points)
    point_dtype = np.float64 if point_array.dtype == np.float64 else np.float32
    vtk_points.SetData(numpy_to_vtk(np.ascontiguousarray(point_array, dtype=point_dtype), deep=True))
    result.SetPoints(vtk_points)
    offsets = np.arange(0, 3 * len(faces) + 1, 3, dtype=np.int64)
    cells = vtk.vtkCellArray()
    cells.SetData(
        numpy_to_vtkIdTypeArray(offsets, deep=True),
        numpy_to_vtkIdTypeArray(np.ascontiguousarray(faces.reshape(-1), dtype=np.int64), deep=True),
    )
    result.SetPolys(cells)
    result.BuildCells()
    return result


def triangle_count(polydata) -> int:
    return int(polydata.GetNumberOfPolys())


def target_edge_length(area: float, source_faces: int, factor: int) -> float:
    target_faces = float(source_faces) / float(factor)
    return math.sqrt(4.0 * area / (math.sqrt(3.0) * target_faces))


def assert_target(polydata, source_faces: int, factor: int, tolerance: float, label: str) -> dict:
    faces = triangle_count(polydata)
    target = float(source_faces) / float(factor)
    relative_error = abs(float(faces) - target) / target
    if relative_error > tolerance:
        raise RuntimeError(
            f"{label} missed {factor}x target: faces={faces:,}, target={target:,.0f}, "
            f"relative_error={relative_error:.2%}, tolerance={tolerance:.2%}."
        )
    return {"output_triangles": faces, "target_triangles": target, "relative_error": relative_error}


def assert_topology_compatible(source: dict, output: dict, label: str) -> None:
    """Reject newly introduced non-manifold or boundary edges in strict audits."""
    source_nonmanifold = int(source["nonmanifold_edges"] or 0)
    output_nonmanifold = int(output["nonmanifold_edges"] or 0)
    if output_nonmanifold > source_nonmanifold:
        raise RuntimeError(
            f"{label} introduced non-manifold edges: source={source_nonmanifold}, output={output_nonmanifold}."
        )
    source_boundary = int(source["boundary_edges"] or 0)
    output_boundary = int(output["boundary_edges"] or 0)
    if output_boundary > source_boundary:
        raise RuntimeError(
            f"{label} introduced boundary edges: source={source_boundary}, output={output_boundary}."
        )


def validate_remesh_mesh(vtk, vtk_to_numpy, polydata, check_topology: bool) -> dict:
    """Validate geometry, with a vectorized exact edge-incidence audit.

    ``vtkFeatureEdges`` is impractically slow on 17M-triangle DrivAerML
    surfaces.  Every undirected triangle edge is encoded as ``lo * N + hi``
    (``N`` is the vertex count), then counted exactly with ``np.unique``.
    This is equivalent to an edge-incidence topology check but completes in
    seconds for multi-million-face remeshes.
    """
    result = validate_mesh(vtk, vtk_to_numpy, polydata, check_topology=False)
    if not check_topology:
        return result
    cells = np.asarray(vtk_to_numpy(polydata.GetPolys().GetData()), dtype=np.int64)
    faces = cells.reshape(-1, 4)[:, 1:]
    vertex_count = int(polydata.GetNumberOfPoints())
    if vertex_count <= 0 or np.any(faces < 0) or np.any(faces >= vertex_count):
        raise RuntimeError("Topology audit found invalid triangle indices.")
    edge_count = faces.shape[0] * 3
    edges = np.empty((edge_count, 2), dtype=np.int64)
    edges[0::3] = faces[:, (0, 1)]
    edges[1::3] = faces[:, (1, 2)]
    edges[2::3] = faces[:, (2, 0)]
    edges.sort(axis=1)
    # DrivAerML has <9M vertices, so this exact encoding remains well inside
    # int64 even for the largest source surface.
    if vertex_count > int(math.isqrt(np.iinfo(np.int64).max)):
        raise RuntimeError("Topology audit vertex range exceeds exact int64 edge-key support.")
    edge_keys = edges[:, 0] * vertex_count + edges[:, 1]
    _, counts = np.unique(edge_keys, return_counts=True)
    result["boundary_edges"] = int(np.count_nonzero(counts == 1))
    result["nonmanifold_edges"] = int(np.count_nonzero(counts > 2))
    return result


def remove_degenerate_faces(points: np.ndarray, faces: np.ndarray) -> np.ndarray:
    """Drop collapsed faces left by vertex clustering without moving vertices."""
    if len(faces) == 0:
        return faces
    triangles = points[faces]
    doubled_area = np.linalg.norm(
        np.cross(triangles[:, 1] - triangles[:, 0], triangles[:, 2] - triangles[:, 0]), axis=1
    )
    diagonal = float(np.linalg.norm(points.max(axis=0) - points.min(axis=0)))
    tolerance = max(np.finfo(points.dtype).eps * max(diagonal * diagonal, 1.0), 1.0e-20)
    keep = np.isfinite(doubled_area) & (doubled_area > tolerance)
    return np.ascontiguousarray(faces[keep], dtype=np.int64)


def remesh_voxel_grid(
    vtk,
    points: np.ndarray,
    faces: np.ndarray,
    source_faces: int,
    source_area: float,
    factor: int,
    args,
):
    """Simplify an existing surface by voxel-grid quadric vertex clustering.

    This is deliberately *not* occupancy voxelization or marching cubes.
    Original vertices are assigned to spatial voxels, each occupied cell is
    contracted by quadric error, and only the original triangles that survive
    the vertex collapse are retained.  Therefore the output follows the
    source surface instead of becoming a blocky voxel isosurface.
    """
    try:
        import open3d as o3d
    except ImportError as exc:  # pragma: no cover - environment setup
        raise RuntimeError("open3d is required for voxel-grid quadric vertex clustering.") from exc

    if len(points) == 0 or len(faces) == 0:
        raise RuntimeError("Voxel clustering requires a nonempty triangular mesh.")
    target_faces = float(source_faces) / float(factor)
    # Quadric-contracted clusters retain more surface detail than an
    # equilateral triangulation at the same cell width. This calibrated start
    # point keeps the target search close for smooth and highly featured meshes.
    voxel_size = target_edge_length(source_area, source_faces, factor) * 0.75
    lower, upper = voxel_size / 2.5, voxel_size * 2.5
    source_mesh = o3d.geometry.TriangleMesh(
        o3d.utility.Vector3dVector(np.ascontiguousarray(points, dtype=np.float64)),
        o3d.utility.Vector3iVector(np.ascontiguousarray(faces, dtype=np.int32)),
    )
    best = None
    try:
        for _ in range(int(args.voxel_adjustments)):
            clustered = source_mesh.simplify_vertex_clustering(
                voxel_size=float(voxel_size),
                contraction=o3d.geometry.SimplificationContraction.Quadric,
            )
            candidate_points = np.asarray(clustered.vertices, dtype=np.float64)
            candidate_faces = remove_degenerate_faces(
                candidate_points,
                np.asarray(clustered.triangles, dtype=np.int64),
            )
            if len(candidate_faces) == 0:
                del clustered
                raise RuntimeError(f"Voxel clustering produced no triangles at cell size={voxel_size:.6g}.")
            candidate = build_polydata(vtk, candidate_points, candidate_faces)
            actual_faces = triangle_count(candidate)
            error = abs(float(actual_faces) - target_faces) / target_faces
            if best is None or error < best[0]:
                best = (error, candidate, voxel_size, int(len(candidate_points)))
            else:
                del candidate
            del clustered, candidate_points, candidate_faces
            if error <= float(args.face_tolerance):
                break
            # Finer cells retain more faces; coarser cells collapse more.
            if actual_faces > target_faces:
                lower = voxel_size
                voxel_size = math.sqrt(voxel_size * upper)
            else:
                upper = voxel_size
                voxel_size = math.sqrt(lower * voxel_size)
    finally:
        del source_mesh

    assert best is not None
    best_error, result, best_voxel_size, output_vertices = best
    return result, {
        "backend": "open3d_voxel_grid_quadric_vertex_clustering_cpu",
        "voxel_size": float(best_voxel_size),
        "output_vertices": output_vertices,
        "best_relative_error": float(best_error),
    }


def remesh_isotropic_explicit(
    vtk,
    vtk_to_numpy,
    points: np.ndarray,
    faces: np.ndarray,
    source_faces: int,
    source_area: float,
    factor: int,
    args,
):
    try:
        import pymeshlab
    except ImportError as exc:  # pragma: no cover - environment setup
        raise RuntimeError("pymeshlab is required for true explicit isotropic remeshing.") from exc

    diagonal = float(np.linalg.norm(points.max(axis=0) - points.min(axis=0)))
    target_faces = float(source_faces) / float(factor)
    target = target_edge_length(source_area, source_faces, factor)

    # Explicit edge operations on the original 16M-face DrivAerML meshes are
    # needlessly expensive. A topology-preserving seed only limits work; the
    # final mesh is still created solely by explicit isotropic operations.
    seed_faces = min(source_faces, max(int(target_faces * float(args.isotropic_seed_multiplier)), int(target_faces)))
    if seed_faces < source_faces and args.isotropic_seed_backend == "vtk_decimate_pro":
        original = build_polydata(vtk, points, faces)
        seed_decimator = vtk.vtkDecimatePro()
        seed_decimator.SetInputData(original)
        seed_decimator.SetTargetReduction(1.0 - float(seed_faces) / float(source_faces))
        seed_decimator.PreserveTopologyOn()
        seed_decimator.BoundaryVertexDeletionOff()
        seed_decimator.SplittingOff()
        seed_decimator.SetFeatureAngle(float(args.feature_angle))
        seed_decimator.Update()
        seed = geometry_only(vtk, seed_decimator.GetOutput())
        seed_points = np.asarray(vtk_to_numpy(seed.GetPoints().GetData()), dtype=np.float32)
        seed_cells = np.asarray(vtk_to_numpy(seed.GetPolys().GetData()), dtype=np.int64)
        if seed_cells.size % 4 != 0 or not np.all(seed_cells[::4] == 3):
            raise RuntimeError("Isotropic seed is not a pure triangular mesh.")
        seed_faces_array = np.ascontiguousarray(seed_cells.reshape(-1, 4)[:, 1:])
        del seed, seed_decimator, seed_cells, original
    elif seed_faces < source_faces:
        # This native MeshLab QEM preconditioner is substantially faster than
        # VTK DecimatePro on the 16M-triangle DrivAerML meshes. It only creates
        # a tractable seed; the final topology is still produced by explicit
        # isotropic split/collapse/flip/smooth/reproject operations below.
        seed_set = pymeshlab.MeshSet()
        seed_set.add_mesh(
            pymeshlab.Mesh(
                vertex_matrix=np.ascontiguousarray(points, dtype=np.float64),
                face_matrix=np.ascontiguousarray(faces, dtype=np.int32),
            )
        )
        seed_set.meshing_decimation_quadric_edge_collapse(
            targetfacenum=int(seed_faces),
            qualitythr=0.3,
            preserveboundary=True,
            boundaryweight=1.0,
            preservenormal=True,
            preservetopology=True,
            optimalplacement=True,
            autoclean=True,
        )
        seed_mesh = seed_set.current_mesh()
        seed_points = np.ascontiguousarray(seed_mesh.vertex_matrix(), dtype=np.float32)
        seed_faces_array = np.ascontiguousarray(seed_mesh.face_matrix(), dtype=np.int64)
        if len(seed_faces_array) == 0:
            raise RuntimeError("MeshLab QEM isotropic seed contains no triangles.")
        del seed_mesh, seed_set
    else:
        seed_points, seed_faces_array = points, faces

    best = None
    lower, upper = target / 2.0, target * 2.0
    current_target = target
    for _ in range(int(args.isotropic_adjustments)):
        # MeshLab accepts a percentage of bounding-box diagonal, not world units.
        target_percent = max(0.0001, 100.0 * current_target / max(diagonal, 1.0e-12))
        mesh_set = pymeshlab.MeshSet()
        mesh_set.add_mesh(
            pymeshlab.Mesh(vertex_matrix=seed_points.astype(np.float64), face_matrix=seed_faces_array.astype(np.int32))
        )
        mesh_set.meshing_isotropic_explicit_remeshing(
            iterations=int(args.isotropic_iterations),
            adaptive=False,
            targetlen=pymeshlab.PercentageValue(target_percent),
            featuredeg=float(args.feature_angle),
            checksurfdist=True,
            maxsurfdist=pymeshlab.PercentageValue(float(args.isotropic_max_surface_distance_percent)),
            splitflag=True,
            collapseflag=True,
            swapflag=True,
            smoothflag=True,
            reprojectflag=True,
        )
        mesh = mesh_set.current_mesh()
        candidate = build_polydata(
            vtk,
            np.ascontiguousarray(mesh.vertex_matrix(), dtype=np.float32),
            np.ascontiguousarray(mesh.face_matrix(), dtype=np.int64),
        )
        actual = triangle_count(candidate)
        error = abs(float(actual) - target_faces) / target_faces
        if best is None or error < best[0]:
            best = (error, candidate, current_target, target_percent)
        else:
            del candidate
        del mesh, mesh_set
        if error <= float(args.face_tolerance):
            break
        # Surface face count scales approximately with h^-2.
        if actual > target_faces:
            lower = current_target
            current_target = math.sqrt(current_target * upper)
        else:
            upper = current_target
            current_target = math.sqrt(lower * current_target)
    assert best is not None
    result = best[1]
    if seed_faces < source_faces:
        del seed_points, seed_faces_array
    return result, {
        "backend": "meshlab_explicit_isotropic_cpu",
        "target_edge_length": best[2],
        "target_edge_percent_bbox_diagonal": best[3],
        "seed_triangles": seed_faces,
        "seed_backend": str(args.isotropic_seed_backend),
        "best_relative_error": float(best[0]),
    }


def remesh_feature_collapse(vtk, vtk_to_numpy, polydata, source_faces: int, factor: int, args):
    """Fast feature-aware edge-collapse for point-cloud source generation."""
    decimator = vtk.vtkDecimatePro()
    decimator.SetInputData(polydata)
    decimator.SetTargetReduction(1.0 - 1.0 / float(factor))
    decimator.PreserveTopologyOn()
    decimator.BoundaryVertexDeletionOff()
    decimator.SplittingOff()
    decimator.SetFeatureAngle(float(args.feature_angle))
    decimator.Update()
    output = geometry_only(vtk, decimator.GetOutput())
    if triangle_count(output) == 0:
        raise RuntimeError("Feature-preserving collapse produced no triangles.")
    return output, {
        "backend": "vtk_decimate_pro_feature_aware_cpu",
        "feature_angle_degrees": float(args.feature_angle),
    }


def remesh_fast_quadric(vtk, vtk_to_numpy, polydata, source_faces: int, factor: int, args):
    """VTK's volume-preserving QEM simplifier.

    The previous third-party unconstrained Fast-QEM backend could create
    non-manifold edges on valid Pump surfaces.  VTK's compiled QEM filter
    reaches the same triangle budgets while retaining a valid closed surface
    on all audited datasets.
    """
    decimator = vtk.vtkQuadricDecimation()
    decimator.SetInputData(polydata)
    decimator.SetTargetReduction(1.0 - 1.0 / float(factor))
    decimator.VolumePreservationOn()
    if hasattr(decimator, "WeighBoundaryConstraintsByLengthOn"):
        decimator.WeighBoundaryConstraintsByLengthOn()
    decimator.Update()
    output = geometry_only(vtk, decimator.GetOutput())
    if triangle_count(output) == 0:
        raise RuntimeError("Quadric remeshing produced no triangles.")
    return output, {"backend": "vtk_volume_preserving_quadric_decimation_cpu"}


def source_paths(args: argparse.Namespace, root: Path) -> list[Path]:
    if args.dataset == "pump":
        requested_ids = {int(item.strip()) for item in args.case_ids.split(",") if item.strip()}
        if not requested_ids:
            requested_ids = set(range(1, int(args.pump_count) + 1))
        if args.max_cases > 0:
            requested_ids = set(sorted(requested_ids)[: int(args.max_cases)])
        missing = [index for index in sorted(requested_ids) if not (root / f"sample_{index:06d}" / "merged_surfaces.vtp").is_file()]
        if missing:
            fetch_pump_sources(args, root, missing)
    paths = sorted(root.glob(DATASET_DEFAULTS[args.dataset]["pattern"]))
    selected_ids = {int(item.strip()) for item in args.case_ids.split(",") if item.strip()}
    if selected_ids:
        paths = [path for path in paths if numeric_id(path) in selected_ids]
    if args.max_cases > 0:
        paths = paths[: int(args.max_cases)]
    if not paths:
        raise FileNotFoundError(f"No source VTPs found under {root}.")
    return paths


def fetch_pump_sources(args: argparse.Namespace, root: Path, indices: Iterable[int]) -> None:
    try:
        from huggingface_hub import hf_hub_download
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError("huggingface_hub is required to retrieve original Pump meshes.") from exc
    root.mkdir(parents=True, exist_ok=True)
    for index in indices:
        sample = f"sample_{index:06d}"
        target = root / sample / "merged_surfaces.vtp"
        if target.is_file():
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        cached = hf_hub_download(
            repo_id=args.pump_repo_id,
            repo_type="dataset",
            revision=args.pump_revision,
            filename=f"{sample}/merged_surfaces.vtp",
            token=os.environ.get("HF_TOKEN") or None,
        )
        shutil.copy2(cached, target)


def remesh_one(path: Path, args: argparse.Namespace, factors: Iterable[int], methods: set[str], output_root: Path) -> list[dict]:
    needs_arrays = bool({"isotropic", "voxel"} & methods)
    vtk, vtk_to_numpy, original, points, faces = load_mesh(path, include_arrays=needs_arrays)
    source_faces = triangle_count(original)
    source_area = float(surface_area(vtk, original))
    source_topology = None
    if args.strict_topology:
        source_topology = validate_remesh_mesh(vtk, vtk_to_numpy, original, check_topology=True)
    case_name = path.parent.name
    records = []
    method_order = [method for method in ("voxel", "quadric", "feature", "isotropic") if method in methods]
    for method in method_order:
        for factor in factors:
            out_dir = output_root / method / case_name
            out_path = out_dir / f"{path.stem}_faces_div{factor}.vtp"
            if out_path.is_file() and not args.overwrite:
                records.append({"input": str(path), "output": str(out_path), "method": method, "factor": factor, "status": "existing"})
                continue
            started = time.perf_counter()
            print(f"[{case_name}] {method} div{factor}: starting", flush=True)
            if method == "voxel":
                if points is None or faces is None:
                    raise RuntimeError("Voxel-grid vertex clustering requires source point and face arrays.")
                output, details = remesh_voxel_grid(vtk, points, faces, source_faces, source_area, factor, args)
            elif method == "quadric":
                output, details = remesh_fast_quadric(vtk, vtk_to_numpy, original, source_faces, factor, args)
            elif method == "isotropic":
                if points is None or faces is None:
                    raise RuntimeError("Isotropic remeshing requires source point and face arrays.")
                output, details = remesh_isotropic_explicit(
                    vtk, vtk_to_numpy, points, faces, source_faces, source_area, factor, args
                )
            else:
                output, details = remesh_feature_collapse(vtk, vtk_to_numpy, original, source_faces, factor, args)
            validation = validate_remesh_mesh(
                vtk,
                vtk_to_numpy,
                output,
                check_topology=bool(args.validate_topology or args.strict_topology),
            )
            if not validation["positive_area"]:
                raise RuntimeError(f"{method} produced zero-area triangles for {path}")
            if source_topology is not None:
                assert_topology_compatible(source_topology, validation, f"{method} for {path.name}")
            counts = assert_target(output, source_faces, factor, float(args.face_tolerance), method)
            write_vtp(vtk, geometry_only(vtk, output), out_path)
            # A VTP is only valid if the same VTK reader can reopen it. This
            # catches malformed XML/appended-data output before it reaches an
            # experiment folder or ParaView.
            persisted = triangulate_if_needed(vtk, read_polydata(vtk, out_path))
            persisted_validation = validate_remesh_mesh(
                vtk,
                vtk_to_numpy,
                persisted,
                check_topology=bool(args.validate_topology or args.strict_topology),
            )
            if source_topology is not None:
                assert_topology_compatible(source_topology, persisted_validation, f"written {method} for {path.name}")
            records.append({
                "input": str(path), "output": str(out_path), "case_id": numeric_id(path),
                "method": method, "factor": factor, "source_triangles": source_faces,
                "seconds": time.perf_counter() - started, "validation": persisted_validation,
                **counts, **details, "status": "ok",
            })
            print(
                f"[{case_name}] {method} div{factor}: {counts['output_triangles']:,} triangles "
                f"in {time.perf_counter() - started:.1f}s",
                flush=True,
            )
            del output
            gc.collect()
    del original
    if points is not None:
        del points
    if faces is not None:
        del faces
    gc.collect()
    return records


def export_example_bundle(paths: list[Path], output_root: Path, results_dir: Path, methods: set[str], factor: int) -> None:
    """Save one inspectable original-plus-remesh VTP/PNG bundle after success."""
    if not paths:
        return
    source = None
    outputs = {}
    for candidate in paths:
        candidate_outputs = {
            method: output_root / method / candidate.parent.name / f"{candidate.stem}_faces_div{factor}.vtp"
            for method in methods
        }
        if all(path.is_file() for path in candidate_outputs.values()):
            source, outputs = candidate, candidate_outputs
            break
    if source is None:
        print(f"[examples] No common completed case at div{factor}; no example bundle written.", flush=True)
        return

    bundle_dir = results_dir / "remeshing_examples" / f"{source.parent.name}_div{factor}"
    bundle_dir.mkdir(parents=True, exist_ok=True)
    copied = {"original": bundle_dir / f"original_{source.name}"}
    shutil.copy2(source, copied["original"])
    for method, path in outputs.items():
        target = bundle_dir / f"{method}_{path.name}"
        shutil.copy2(path, target)
        copied[method] = target

    # A compact raster preview is easier to inspect than multi-million-face VTPs.
    import matplotlib.pyplot as plt
    from mpl_toolkits.mplot3d.art3d import Poly3DCollection

    vtk, vtk_to_numpy = require_vtk()
    panels = [("Original", copied["original"])] + [(method.title(), copied[method]) for method in sorted(methods)]
    fig = plt.figure(figsize=(5.5 * len(panels), 5.0), constrained_layout=True)
    for index, (label, path) in enumerate(panels, start=1):
        poly = triangulate_if_needed(vtk, read_polydata(vtk, path))
        pts = np.asarray(vtk_to_numpy(poly.GetPoints().GetData()), dtype=np.float32)
        cells = np.asarray(vtk_to_numpy(poly.GetPolys().GetData()), dtype=np.int64).reshape(-1, 4)[:, 1:]
        # mplot3d depth-sorts every polygon in Python. A small deterministic
        # subset stays visually representative without delaying the pipeline.
        limit = min(len(cells), 12_000)
        selected = cells[np.linspace(0, len(cells) - 1, limit, dtype=np.int64)]
        axis = fig.add_subplot(1, len(panels), index, projection="3d")
        axis.add_collection3d(Poly3DCollection(pts[selected], facecolor="#71a8d0", edgecolor="none", alpha=1.0))
        mins, maxs = pts.min(axis=0), pts.max(axis=0)
        axis.set_xlim(mins[0], maxs[0])
        axis.set_ylim(mins[1], maxs[1])
        axis.set_zlim(mins[2], maxs[2])
        axis.set_box_aspect(np.maximum(maxs - mins, 1.0e-8))
        axis.view_init(elev=18, azim=-62)
        axis.set_axis_off()
        axis.set_title(label, fontsize=14, fontweight="bold")
    preview = bundle_dir / "original_and_remeshes.png"
    fig.savefig(preview, dpi=220, bbox_inches="tight")
    plt.close(fig)
    (bundle_dir / "example_manifest.json").write_text(
        json.dumps({"source": str(source), "factor": factor, "files": {key: str(value) for key, value in copied.items()}}, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"[examples] Wrote VTP and PNG bundle to {bundle_dir}", flush=True)


def main() -> int:
    args = parse_args()
    factors = parse_ints(args.factors)
    methods = {item.strip().lower() for item in args.methods.split(",") if item.strip()}
    if methods - {"voxel", "quadric", "isotropic", "feature"} or not methods:
        raise ValueError("--methods must be a nonempty subset of voxel,quadric,isotropic,feature.")
    if not 0.0 < args.face_tolerance <= 0.25:
        raise ValueError("--face-tolerance must lie in (0, 0.25].")
    if args.workers <= 0:
        raise ValueError("--workers must be positive.")
    defaults = DATASET_DEFAULTS[args.dataset]
    source_root = (args.source_dir or defaults["source_dir"]).expanduser().resolve()
    output_root = (args.output_dir or defaults["output_dir"]).expanduser().resolve()
    results_dir = (args.results_dir or SMART_ROOT.parent / "results" / f"{args.dataset}_surface_remesh_v2").expanduser().resolve()
    output_root.mkdir(parents=True, exist_ok=True)
    results_dir.mkdir(parents=True, exist_ok=True)
    paths = source_paths(args, source_root)
    print(
        f"Remeshing {len(paths)} {args.dataset} meshes with methods={sorted(methods)}, factors={factors}, "
        f"tolerance={args.face_tolerance:.0%}.", flush=True,
    )
    records = []
    failures = []
    # Create the inspectable original-plus-remesh bundle before scheduling the
    # bulk conversion. This makes the first source mesh an immediate visual
    # gate rather than a post-processing artifact at the end of a long run.
    all_paths = paths
    first_path, remaining_paths = all_paths[0], all_paths[1:]
    try:
        records.extend(remesh_one(first_path, args, factors, methods, output_root))
    except Exception as exc:
        raise RuntimeError(f"First source mesh failed; no bulk remeshing started: {first_path}") from exc
    example_factor = int(args.example_factor)
    if example_factor not in factors:
        example_factor = max(factors)
    export_example_bundle([first_path], output_root, results_dir, methods, example_factor)
    paths = remaining_paths
    # Every method is CPU/VTK based. Keep all work for one source mesh in one
    # process, which avoids duplicating its large VTP decode across methods.
    workers = min(int(args.workers), len(paths)) if paths else 0
    # A one-case audit gains nothing from a forked worker and VTK's native
    # objects are safer to diagnose in the owning process. Production runs
    # with multiple meshes still use the bounded process pool below.
    executor = None
    futures = {}
    if workers == 1:
        for path in tqdm(paths, desc="Validated remeshing"):
            try:
                records.extend(remesh_one(path, args, factors, methods, output_root))
            except Exception as exc:
                failures.append({"input": str(path), "methods": sorted(methods), "error": repr(exc)})
                print(f"[failure] remeshing {path}: {exc}", flush=True)
                if args.fail_fast:
                    raise
    elif workers > 1:
        executor = ProcessPoolExecutor(max_workers=workers)
        futures = {
            executor.submit(remesh_one, path, args, factors, methods, output_root): path
            for path in paths
        }
    try:
        if futures:
            for future in tqdm(as_completed(futures), total=len(futures), desc="Validated remeshing"):
                try:
                    records.extend(future.result())
                except Exception as exc:
                    path = futures[future]
                    failures.append({"input": str(path), "methods": sorted(methods), "error": repr(exc)})
                    print(f"[failure] remeshing {path}: {exc}", flush=True)
                    if args.fail_fast:
                        raise
    finally:
        if executor is not None:
            executor.shutdown(wait=True, cancel_futures=False)
    if args.dataset == "pump" and args.delete_pump_source_after_success:
        for path in all_paths:
            case_name = path.parent.name
            expected = [
                output_root / method / case_name / f"{path.stem}_faces_div{factor}.vtp"
                for method in methods
                for factor in factors
            ]
            if all(item.is_file() for item in expected):
                shutil.rmtree(path.parent)
    records.sort(key=lambda row: (int(row.get("case_id", -1)), row["method"], int(row["factor"])))
    summary = {
        "dataset": args.dataset, "source_dir": str(source_root), "output_dir": str(output_root),
        "results_dir": str(results_dir),
        "methods": sorted(methods), "factors": factors, "face_tolerance": float(args.face_tolerance),
        "validate_topology": bool(args.validate_topology),
        "strict_topology": bool(args.strict_topology),
        "failures": failures,
        "method_definitions": {
            "voxel": "Open3D voxel-grid vertex clustering with quadric-contracted cluster representatives",
            "quadric": "VTK volume-preserving quadric-error simplification",
            "isotropic": "MeshLab explicit isotropic remeshing: split/collapse/flip/smooth/reproject",
            "feature": "VTK topology-preserving feature-aware edge-collapse",
        },
        "records": records,
    }
    (output_root / "remeshing_v2_summary.json").write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(records)} outputs to {output_root}", flush=True)
    if failures:
        raise RuntimeError(f"Remeshing completed with {len(failures)} failed case(s); see remeshing_v2_summary.json.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
